spring:
  application:
    name: demo-kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      isolation-level: read_committed
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    producer:
      transaction-id-prefix: ${spring.application.name}-tx-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
  docker:
    compose:
      lifecycle-management: start_only
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    root: warn
    io.github.rdlopes: info
server:
  port: 8082
